services:
  database:
    image: postgres:16-alpine
    ports:
      - '${DB_PORT:-4321}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME:-local}
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
  cache:
    image: redis
    ports:
      - '${REDIS_PORT:-5002}:6379'
volumes:
  pgdata:
