services:
  database:
    image: postgres:16-alpine
    ports:
      - '${DB_PORT:-4321}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME:-local}
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
  cache:
    image: redis
    ports:
      - '${REDIS_PORT:-5002}:6379'
  rabbitmq:
    image: 'rabbitmq:3-management'
    hostname: 'rabbitmq'
    container_name: 'rabbitmq-server'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER:-user}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD:-password}
    ports:
      - '${RABBIT_PORT:-5671}:5672' # Porta padrão do RabbitMQ
      - '${RABBIT_WEB_PORT:-15671}:15672' # Porta da interface de gerenciamento web
volumes:
  pgdata:
